version: '3.8'

services:
  home-page:
    image: ghcr.io/evanschalton/portainer-homepage:latest
    ports:
      - "80:80"
    environment:
      - service_placeholder_label=placeholder
      - service_placeholder_url=placeholder-url
      - service_portainer_label=Portainer
      - service_portainer_url=https://docker.lan:9443
      - service_neo4j_label=Neo4j
      - service_neo4j_url=https://docker.lan:7474/browser/

