# name: Release Please

# on:
#   push:
#     branches: [main]

# jobs:
#   release:
#     runs-on: ubuntu-latest

#     permissions:
#       contents: write
#       pull-requests: write
#       issues: write

#     steps:
#       - uses: googleapis/release-please-action@v4
#         with:
#           release-type: simple
